### ISSUE TITLE
Example support for 3rd party logging service, eg. Papertrail

### ISSUE THREAD

**Issue by moflo** [twitter/ios-twitter-logging-service#11]
Congratulations on releasing this! It would be helpful to have more pointers on how to create output streams for existing 3rd party services. Would especially like to see in the README  (#10)  how to extend TLS to support  Papertrail, for example.

Thanks!

**Comment by NSProgrammer** [comment]
There are several concretely implemented output streams already implemented in TLS.  They can all stand as examples on how to create a new output stream.  The TLSOutputStream protocol is well documented too.

I'm going to resolve this but feel free to create an issue for your specific request regarding a Papertrail output stream and maybe there will be a contributor that is will to take that on.
