### ISSUE TITLE
compile error after pod install

### ISSUE THREAD

**Issue by nillcui** [twitter/ios-twitter-logging-service#17]
install via pod 'TwitterLoggingService', '~> 2.3.0'
Xcode 10.2.1 compile error below:
Value for SWIFT_VERSION cannot be empty. (in target 'TwitterLoggingService')

if I set the Swift Language Version to (Swift5/Swift4.2/Swift4),  the TLSLog.swift has many error:
..../Pods/TwitterLoggingService/Classes/TLSLog.swift:34:90: Attribute can only be applied to types, not declarations
..../Pods/TwitterLoggingService/Classes/TLSLog.swift:48:47: Attribute can only be applied to types, not declarations
and etc...

thanks !

**Comment by NSProgrammer** [comment]
Sorry, the latest pod is actually `2.5.0`

I've updated the README to reflect this

`pod 'TwitterLoggingService', '~> 2.5.0'`
