### ISSUE TITLE
File log issue

### ISSUE THREAD

**Issue by evolkov** [twitter/ios-twitter-logging-service#8]
Logging in file doesn't work. I try to use your solution for file logging but even in our example application for iOS log files are empty after using. 
Maybe I don't understand how to use our logging service.

**Comment by NSProgrammer** [comment]
something you might need to consider it I/O buffering.  The file output stream will output to a file descriptor but for system performance an I/O write doesn't happen synchronously, it gets buffered until either the descriptor buffers enough output to write to disk, is closed or is explicitly flushed.

For debugging, you can used the exposed property on the file output stream to explicitly flush on every write.

```objc
/**
 Enable flushing after every write.  Expensive with I/O, should only be used for debugging.
 Default is `NO`.
 */
@property (nonatomic, getter=isFlushAfterEveryWriteEnabled) BOOL flushAfterEveryWriteEnabled;
```

This is EXPENSIVE on the hardware and should not be used in production.  In production, you'll want to let things buffer until there's a point in time you truly need the output to be on disk, at which point you should flush your output streams:

```objc
@interface TLSLoggingService (Advanced)

// ...

/**
 synchronously flushes all internal queues and calls flush on all `TLSOutputStream`s that implement `flush`
 */
- (void)flush;

// ...

@end
```


At Twitter, we flush in the following circumstances:

1. App backgrounding
2. Crash detection (Just-In-Time crash handling will flush)
3. Log reading (such as when we zip up the logs to send with bug reports)

I hope this helps.

**Comment by NSProgrammer** [comment]
Closing this for now as I see no other indication other than "flush" to be the issue
